language: go
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
script:
  - go get golang.org/x/tools/cmd/goyacc
  - go install golang.org/x/tools/cmd/goyacc
  - go generate ./...
  - go vet ./...

  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken $COVERALLS_TOKEN
